pipeline {
    agent any

    environment {
        CI = 'true'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                sh 'npm install'
            }
        }

        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('sonarqube') {
                    sh """
                    /var/lib/jenkins/tools/hudson.plugins.sonar.SonarRunnerInstallation/sonarscanner/bin/sonar-scanner \
                    -Dsonar.projectKey=week12-project \
                    -Dsonar.sources=./src
                    """
                }
            }
        }

        stage('Deliver') {
            steps {
                echo 'Deliver/Deploy step'
                // sh './jenkins/scripts/deliver.sh'
            }
        }
    }

    post {
        always {
            echo 'Pipeline finished.'
            echo 'Check SonarQube dashboard at: http://98.93.242.179:9000/dashboard?id=week12-project'
        }
    }
}
